update push docker images action

diff --git a/.github/actions/plan/push-docker-images/action.yml b/.github/actions/plan/push-docker-images/action.yml
--- a/.github/actions/plan/push-docker-images/action.yml
+++ b/.github/actions/plan/push-docker-images/action.yml
@@ -19,8 +19,15 @@ runs:
     - name: Configure AWS Credentials
       shell: bash
       run: |
+        if [ -z "${{ inputs.aws_access_key_id }}" ] || [ -z "${{ inputs.aws_secret_access_key }}" ] || [ -z "${{ inputs.aws_region }}" ]; then
+          echo "One or more required inputs are missing."
+          exit 1
+        fi
+        echo "Configuring AWS Access Key ID"
         aws configure set aws_access_key_id ${{ inputs.aws_access_key_id }}
+        echo "Configuring AWS Secret Access Key"
         aws configure set aws_secret_access_key ${{ inputs.aws_secret_access_key }}
+        echo "Configuring AWS Default Region"
         aws configure set default.region ${{ inputs.aws_region }}
     - name: Login to Amazon ECR
       shell: bash
@@ -31,8 +38,11 @@ runs:
       run: |
         for image in docker-images/*.tgz; do
           # Extract image name and tag from filename
-          IMAGE_NAME=$(basename "$image" .tgz)
+          IMAGE=$(basename "$image" .tgz)
+          IMAGE_NAME=${IMAGE%_*}
+          IMAGE_TAG=${IMAGE%*_}
           echo $IMAGE_NAME
+          echo $IMAGE_TAG
           # # Load the Docker image from .tgz file
           # docker load < "$image"
           
@@ -40,8 +50,8 @@ runs:
           # aws ecr describe-repositories --repository-names "$IMAGE_NAME" || aws ecr create-repository --repository-name "$IMAGE_NAME"
           
           # # Tag the image for ECR
-          # docker tag "$IMAGE_NAME" ${{ inputs.ecr_account_id }}.dkr.ecr.${{ inputs.aws_region }}.amazonaws.com/"$IMAGE_NAME"
+          # docker tag "$IMAGE_NAME" ${{ inputs.ecr_account_id }}.dkr.ecr.${{ inputs.aws_region }}.amazonaws.com/"$IMAGE_NAME":"$IMAGE_TAG"
           
           # # Push the image to ECR
-          # docker push ${{ inputs.ecr_account_id }}.dkr.ecr.${{ inputs.aws_region }}.amazonaws.com/"$IMAGE_NAME"
+          # docker push ${{ inputs.ecr_account_id }}.dkr.ecr.${{ inputs.aws_region }}.amazonaws.com/"$IMAGE_NAME":"$IMAGE_TAG"
         done
