add aws configure step to terraform aply action

diff --git a/.github/actions/deploy/terraform-apply/action.yml b/.github/actions/deploy/terraform-apply/action.yml
--- a/.github/actions/deploy/terraform-apply/action.yml
+++ b/.github/actions/deploy/terraform-apply/action.yml
@@ -3,6 +3,19 @@ description: "Check for IAC directory and run terraform apply if exists"
 runs:
   using: "composite"
   steps:
+    - name: Configure AWS Credentials
+      shell: bash
+      run: |
+        if [ -z "${{ inputs.aws_access_key_id }}" ] || [ -z "${{ inputs.aws_secret_access_key }}" ] || [ -z "${{ inputs.aws_region }}" ]; then
+          echo "One or more required inputs are missing."
+          exit 1
+        fi
+        echo "Configuring AWS Access Key ID"
+        aws configure set aws_access_key_id ${{ inputs.aws_access_key_id }}
+        echo "Configuring AWS Secret Access Key"
+        aws configure set aws_secret_access_key ${{ inputs.aws_secret_access_key }}
+        echo "Configuring AWS Default Region"
+        aws configure set default.region ${{ inputs.aws_region }}
     - name: Terraform apply
       shell: bash
       run: |
